export default {
	"pages": {
		"root": {
			"name": "root",
			"children": [
				"64234a00aed6310020be637b",
				"64234a01aed6310020be637f",
				"64234a01aed6310020be6383",
				"64234a01aed6310020be638b",
				"642f62c9aed6310020bf0f81"
			],
			"id": "root",
			"pageUrl": "root"
		},
		"64234a00aed6310020be637b": {
			"id": "64234a00aed6310020be637b",
			"name": "404",
			"pageUrl": "404"
		},
		"64234a01aed6310020be637f": {
			"id": "64234a01aed6310020be637f",
			"name": "index",
			"pageUrl": "index",
			"seo": {
				"og:description": "It all begins with an idea. Maybe you want to launch a business. Maybe you want to turn a hobby into something bigger. Or maybe you have a creative project to share with the world. Whatever it is, the way you tell your story online can make all the difference.",
				"title": "Home | Website Example",
				"og:title": "Home | Website Example",
				"og:image": "https://uploads.quarkly.io/5f44d0da669357001e60ed14/images/website-example-quarkly.png?v=2020-11-05T19:48:01.806Z",
				"description": "It all begins with an idea. Maybe you want to launch a business. Maybe you want to turn a hobby into something bigger. Or maybe you have a creative project to share with the world. Whatever it is, the way you tell your story online can make all the difference."
			}
		},
		"64234a01aed6310020be6383": {
			"id": "64234a01aed6310020be6383",
			"pageUrl": "about",
			"name": "How it Works",
			"seo": {
				"og:title": "About | Website Example",
				"og:description": "It all begins with an idea. Maybe you want to launch a business. Maybe you want to turn a hobby into something bigger. Or maybe you have a creative project to share with the world. Whatever it is, the way you tell your story online can make all the difference.",
				"description": "It all begins with an idea. Maybe you want to launch a business. Maybe you want to turn a hobby into something bigger. Or maybe you have a creative project to share with the world. Whatever it is, the way you tell your story online can make all the difference.",
				"og:image": "https://uploads.quarkly.io/5f44d0da669357001e60ed14/images/website-example-quarkly.png?v=2020-11-05T19:48:01.806Z",
				"title": "About | Website Example"
			}
		},
		"64234a01aed6310020be638b": {
			"id": "64234a01aed6310020be638b",
			"seo": {
				"description": "It all begins with an idea. Maybe you want to launch a business. Maybe you want to turn a hobby into something bigger. Or maybe you have a creative project to share with the world. Whatever it is, the way you tell your story online can make all the difference.",
				"og:description": "It all begins with an idea. Maybe you want to launch a business. Maybe you want to turn a hobby into something bigger. Or maybe you have a creative project to share with the world. Whatever it is, the way you tell your story online can make all the difference.",
				"og:image": "https://uploads.quarkly.io/5f44d0da669357001e60ed14/images/website-example-quarkly.png?v=2020-11-05T19:48:01.806Z",
				"title": "Team | Website Example",
				"og:title": "Team | Website Example"
			},
			"pageUrl": "team",
			"name": "Team"
		},
		"642f62c9aed6310020bf0f81": {
			"id": "642f62c9aed6310020bf0f81",
			"pageUrl": "privacy-policytos",
			"name": "Privacy Policy/TOS"
		}
	},
	"mode": "production",
	"projectType": "create-react-app",
	"site": {
		"styles": {
			"font": "18px --fontFamily-sans"
		},
		"seo": {
			"title": "Disko",
			"description": "Take the stress out of event planning with our powerful RSVP platform. Share events, track analytics, and discover new events on our dynamic event feed. Event marketing has never been so easy\n",
			"og:title": "RSVP for Upcoming Events",
			"robotsFileType": "autogenerated",
			"og:image": "https://uploads.quarkly.io/64234a00aed6310020be6362/images/Frame%207.png?v=2023-04-02T18:46:27.087Z",
			"og:description": "Join us for upcoming events and RSVP directly on our website. Stay up to date with event details and connect with other attendees."
		}
	}
}